name = "midori"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.37.0"
wisp = "~> 0.8"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
mist = ">= 0.17.0 and < 1.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
ids = "~> 0.11"
gchess = { path = "gchess" }
gleam_json = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
