name = "ui"
version = "0.1.0"
target = "javascript"

[dependencies]
gchessboard = { path = "gchessboard" }
gleam_stdlib = "~> 0.32"
lustre = "~> 3.0"
gleam_javascript = "~> 0.8"

[dev-dependencies]
gleeunit = "~> 1.0"
